### Семинар 6. Метод опорных векторов (SVM)

из материалов спецкурсе «Введение в компьютерный интеллект. Машинное обучение» механико-математического факультета МГУ.

In [14]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [2]:
X, y = load_breast_cancer(return_X_y=True)

In [3]:
trainX, testX, trainY, testY = train_test_split(X, y, random_state=42, test_size=0.2)
print(trainX.shape, trainY.shape, testX.shape, testY.shape)

(455, 30) (455,) (114, 30) (114,)


In [4]:
print(testY)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0]


### Linear SVM

In [5]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=42).fit(trainX, trainY)
out_y = clf.predict(testX)
print(out_y)

[1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1
 1 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 1 1 1 1 0 1 1 0
 1 1 0]


/Users/Artem/opt/anaconda2/envs/Ds/lib/python3.7/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Можно посмотреть сами значения, по которым принимается решение (берется sign)

In [6]:
import numpy as np
scores = clf.decision_function(testX)
print(scores)
print((scores > 0).astype(np.int32) == out_y)

[  1.18851439  -2.89392783  -0.12734253   2.29771155   2.21973379
  -1.84421241  -3.43893656   0.57467205   2.14177447   1.80669524
   1.66317853  -0.25239285   1.95122326   1.50436011   1.9997518
   0.97943449   2.16712509   2.12205657   1.47661689  -1.1730284
   1.22441216   1.66805285  -2.23187008   1.66544424   1.82179585
   2.52342397   2.17161281   1.83934131   1.97142015  -2.56909764
   1.92717078   2.04028295   1.38363863   1.44927131   1.91445309
   1.78048706  -0.10670635   1.62161053  -1.41533354   1.53883472
   1.88433504  -0.11270409   2.21348899   1.6690105    2.12156575
   1.45616004   1.85080457   1.38623889   1.4666477    2.11665562
  -0.9729704   -2.03834992   1.85235323   2.27527816   2.20659616
   1.58949521   1.95336909  -3.44511832   1.3890462    2.20050965
   1.79540371  -1.25128027  -2.5863754    1.79921929   1.81930486
   1.53324735  -0.68456497  -0.43563365   1.97609357   1.83613624
   0.63081129  -1.027425     2.03570592   1.49916583   1.14216671
   2.1476362

Можно распечатать коэффициенты линейного классификатора и его свободный член

In [7]:
print('w =', clf.coef_)
print('w0 =', clf.intercept_)

w = [[ 3.45386703e-02  2.00806900e-02  7.64178014e-02  4.94928531e-04
  -6.29510508e-04 -4.20627087e-03 -5.67596874e-03 -2.31336030e-03
  -8.71485683e-04 -1.67033859e-04  1.04266071e-03  6.32117496e-03
  -6.45348580e-03 -8.45928174e-03 -2.70431797e-05 -1.03113061e-03
  -1.26265678e-03 -3.29641789e-04 -2.16910389e-04 -7.91469278e-05
   3.54975245e-02 -3.85068140e-02 -1.79731405e-02 -5.36445901e-03
  -1.25172012e-03 -1.49058611e-02 -1.74979726e-02 -4.91592845e-03
  -3.62856882e-03 -1.20501081e-03]]
w0 = [0.00610667]


In [8]:
out_score = clf.score(testX, testY)
print('Linear score:', out_score)

Linear score: 0.8947368421052632


### Kernel SVM

In [9]:
from sklearn.svm import SVC
clf = SVC(random_state=42, C=1.0, kernel='poly', degree=3, gamma='scale').fit(trainX, trainY)
out_y = clf.predict(testX)
print(out_y)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0]


Можно посмотреть количество опорных векторов для каждого класса, их индексы, а также сами опорные вектора

In [10]:
print(clf.n_support_)
print(clf.support_)
print(clf.support_vectors_)

[60 60]
[  5  17  21  25  30  34  36  50  55  71  95 100 106 120 121 130 134 141
 145 147 155 162 183 193 197 202 236 283 285 286 306 309 310 312 323 324
 327 329 332 335 352 353 354 357 360 362 364 365 391 394 397 398 403 409
 413 435 441 445 446 453   6  18  20  24  35  39  44  53  57  59  61  63
  65  66  72  73  82  86 107 117 124 129 133 136 144 149 160 171 180 203
 204 207 223 229 230 239 241 247 262 269 272 281 282 284 290 299 305 334
 355 358 380 382 395 405 415 419 422 436 437 439]
[[1.454e+01 2.754e+01 9.673e+01 ... 1.712e-01 4.218e-01 1.341e-01]
 [1.522e+01 3.062e+01 1.034e+02 ... 2.356e-01 4.089e-01 1.409e-01]
 [1.534e+01 1.426e+01 1.025e+02 ... 2.393e-01 4.667e-01 9.946e-02]
 ...
 [1.499e+01 2.211e+01 9.753e+01 ... 1.308e-01 3.163e-01 9.251e-02]
 [1.785e+01 1.323e+01 1.146e+02 ... 8.341e-02 1.783e-01 5.871e-02]
 [1.350e+01 1.271e+01 8.569e+01 ... 2.210e-02 2.267e-01 6.192e-02]]


In [12]:
i=0
idx = clf.support_[i]
import numpy as np
print('train vector == support vector: ', np.all(trainX[idx] == clf.support_vectors_[i]))

train vector == support vector:  True


In [13]:
out_score = clf.score(testX, testY)
print('Poly score:', out_score)

Poly score: 0.9473684210526315


### См. также

- LibSVM - https://www.csie.ntu.edu.tw/~cjlin/libsvm/ - с++/Java реализация SVM общего вида со множеством интерфейсов в сторонних ЯП
- LibLinear - https://www.csie.ntu.edu.tw/~cjlin/liblinear/ - версия LibSVM исключительно для линейного ядра (работает в этом случае гораздо быстрее)

### Сравним с некоторой нейронной сетью

In [16]:
import keras

In [52]:
model = keras.Sequential()
model.add(keras.Input(shape=(30,)))
model.add(keras.layers.Dense(15, activation="relu"))
model.add(keras.layers.Dense(7, activation="relu"))
model.add(keras.layers.Dense(1, activation="relu"))

model.compile(optimizer='SGD', loss='binary_crossentropy')

model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 15)                465       
_________________________________________________________________
dense_22 (Dense)             (None, 7)                 112       
_________________________________________________________________
dense_23 (Dense)             (None, 1)                 8         
Total params: 585
Trainable params: 585
Non-trainable params: 0
_________________________________________________________________


In [53]:
trX=trainX/trainX.max()

In [56]:
model.fit(trX, trainY, epochs=30)

Epoch 1/30
15/15 [==============================] - 0s 1ms/step - loss: 0.3062
Epoch 2/30
15/15 [==============================] - 0s 2ms/step - loss: 0.2997
Epoch 3/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2944
Epoch 4/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2902
Epoch 5/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2908
Epoch 6/30
15/15 [==============================] - 0s 970us/step - loss: 0.2784
Epoch 7/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2964
Epoch 8/30
15/15 [==============================] - 0s 929us/step - loss: 0.2753
Epoch 9/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2816
Epoch 10/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2845
Epoch 11/30
15/15 [==============================] - 0s 1ms/step - loss: 0.2817
Epoch 12/30
15/15 [==============================] - 0s 1ms/step - loss: 0.3001
Epoch 13/30
15/15 [==========================

In [58]:
tsX=testX/testX.max()

In [59]:
pred=model.predict(tsX)

In [65]:
res=np.mean(pred-testY)

In [66]:
res

-0.1471939808443973